chore: refactor history management and update documentation

diff --git a/gh-find-code b/gh-find-code
--- a/gh-find-code
+++ b/gh-find-code
@@ -103,7 +103,7 @@ fzf_prompt_helpABC=$(printf "%b?? Help: %b" "$CYAN_NORMAL" "$COLOR_RESET")
 
 FZF_API_KEY=$(command head -c 32 /dev/urandom | command base64)
 GHFC_HISTORY_LIMIT=${GHFC_HISTORY_LIMIT:-500}
-gh_find_code_history="${BASH_SOURCE%/*}/gh_find_code_history.txt"
+GHFC_HISTORY_FILE=${GHFC_HISTORY_FILE:-${BASH_SOURCE%/*}/gh_find_code_history.txt}
 
 # A cached version will be used before a new one is pulled.
 gh_default_cache_time="1h"
@@ -137,7 +137,7 @@ store_skip_count="${scratch_directory}/skip_count"
 store_query_pids="${scratch_directory}/query_pids"
 store_fuzzy_search_string="${scratch_directory}/fuzzy_search_string"
 store_search_string="${scratch_directory}/search_string"
-store_gh_find_code_history_tmp="${scratch_directory}/gh_find_code_history_tmp"
+store_history_tmp="${scratch_directory}/history_tmp"
 store_gh_api_error="${scratch_directory}/gh_api_error"
 store_gh_search_error="${scratch_directory}/gh_search_error"
 store_hold_gh_query_loop="${scratch_directory}/hold_gh_query_loop"
@@ -261,9 +261,22 @@ validate_environment() {
 		die "GHFC_HISTORY_LIMIT must be a number."
 	fi
 
+	# Check if the necessary history file exists and is readable and writable
+	if ((GHFC_HISTORY_LIMIT)); then
+		if [[ -d $GHFC_HISTORY_FILE ]]; then
+			die "$GHFC_HISTORY_FILE is a directory"
+		fi
+		if [[ ! -f $GHFC_HISTORY_FILE ]]; then
+			touch "$GHFC_HISTORY_FILE" || die "Unable to create: $GHFC_HISTORY_FILE"
+		fi
+		[[ -r $GHFC_HISTORY_FILE ]] || die "Permission denied: unable to read from: $GHFC_HISTORY_FILE"
+		[[ -w $GHFC_HISTORY_FILE ]] || die "Permission denied: unable to write to: $GHFC_HISTORY_FILE"
+
+	fi
+
 	# If the history file is empty and GHFC_HISTORY_LIMIT is greater than zero, add some examples.
-	if [[ ! -s $gh_find_code_history ]] && ((GHFC_HISTORY_LIMIT)); then
-		command cat <<'EOF' >"$gh_find_code_history"
+	if [[ ! -s $GHFC_HISTORY_FILE ]] && ((GHFC_HISTORY_LIMIT)); then
+		command cat <<'EOF' >"$GHFC_HISTORY_FILE"
 repo:junegunn/fzf FZF_PORT
 extension:rs "Hello, world!"
 EOF
@@ -344,17 +357,17 @@ open_query_in_browser() {
 
 # Adding the current value for 'FZF_QUERY', exported by 'fzf', to the history file.
 add_history() {
-	echo "$FZF_QUERY" >>"$gh_find_code_history"
+	echo "$FZF_QUERY" >>"$GHFC_HISTORY_FILE"
 	# To avoid duplicates, only the most recent entry is retained. Since 'tail -r' does not work
 	# with the 'coreutils' version and 'tac' requires 'coreutils', 'sed' is used to reverse the
 	# order of lines. Be cautious not to read from and write to the same file in the same pipeline
 	# to prevent a race condition that could erase the file. See: https://shellcheck.net/wiki/SC2094
 	# for more information.
-	if command sed '1!G;h;$!d' "$gh_find_code_history" | command awk '{$1=$1}; NF && !x[$0]++' |
+	if command sed '1!G;h;$!d' "$GHFC_HISTORY_FILE" | command awk '{$1=$1}; NF && !x[$0]++' |
 		command grep --invert-match --regexp='^$' | command sed '1!G;h;$!d' |
-		command tail -n "$GHFC_HISTORY_LIMIT" >"$store_gh_find_code_history_tmp"; then
+		command tail -n "$GHFC_HISTORY_LIMIT" >"$store_history_tmp"; then
 
-		command mv "$store_gh_find_code_history_tmp" "$gh_find_code_history"
+		command mv "$store_history_tmp" "$GHFC_HISTORY_FILE"
 	fi
 }
 
@@ -362,9 +375,9 @@ add_history() {
 remove_history() {
 	# Attach '--regexp' directly to its argument to handle leading dashes.
 	command grep --fixed-strings --line-regexp --invert-match --regexp="$*" \
-		"$gh_find_code_history" >"$store_gh_find_code_history_tmp"
+		"$GHFC_HISTORY_FILE" >"$store_history_tmp"
 
-	command mv "$store_gh_find_code_history_tmp" "$gh_find_code_history"
+	command mv "$store_history_tmp" "$GHFC_HISTORY_FILE"
 }
 
 show_api_limits() {
@@ -786,13 +799,13 @@ fzf_basic_style() {
 
 view_history_commands() {
 	local header_string header_color history_command selection
-	if [[ ! -s $gh_find_code_history ]]; then
+	if [[ ! -s $GHFC_HISTORY_FILE ]]; then
 		header_color="yellow"
 		header_string="No history entries yet. Check back on your next run. Press 'esc' to exit."
 	fi
 	echo "hold" >"$store_hold_gh_query_loop"
 	# The additional pipe for 'bat' is used to improve text visibility.
-	history_command=$'command sed \'1!G;h;$!d\' "$gh_find_code_history" | command nl -s "\t" -n ln -w 3 | command '$bat_executable' --plain --color=always'
+	history_command=$'command sed \'1!G;h;$!d\' "$GHFC_HISTORY_FILE" | command nl -s "\t" -n ln -w 3 | command '$bat_executable' --plain --color=always'
 	# The Ctrl+C keybind instantly closes 'fzf' by terminating both instances.
 	selection=$(
 		fzf_basic_style \
