chore: use temp directories, easier to cleanup

diff --git a/gh-find-code b/gh-find-code
--- a/gh-find-code
+++ b/gh-find-code
@@ -51,55 +51,47 @@ DARK_GRAY='\033[0;90m'
 
 # =========================== basics ============================
 
-trap cleanup EXIT SIGHUP SIGINT
+cleanup() {
+	$debug_mode && printf "%bDebug mode was ON, the following files weren't deleted.%b\n" "$YELLOW_NORMAL" "$COLOR_RESET"
+	rm -rf "$scratch_directory" 2>/dev/null
+	if ! $debug_mode; then
+		rm -rf "$debug_directory" 2>/dev/null
+	else
+		find "${debug_directory}/"* 2>/dev/null | while read -r matching_file; do
+			if [[ ! -s $matching_file ]]; then
+				rm -f "$matching_file"
+			else
+				printf "\t%s\n" "$matching_file"
+			fi
+		done
+	fi
+}
 
 die() {
 	echo ERROR: "$*" >&2
 	exit 1
 }
 
+trap cleanup EXIT SIGHUP SIGINT
+
 # Creating temporary files. The current setup works but is very verbose. An attempt to use
 # associative arrays with 'declare -A' was unsuccessful as I couldn't access the associated
 # filename in child processes.
-store_bat_debug=$(mktemp -t bat_debug) || die "Can't create temp file."
-store_file_contents=$(mktemp -t file_content) || die "Can't create temp file."
-store_fzf_port=$(mktemp -t fzf_port) || die "Can't create temp file."
-store_gh_content_debug=$(mktemp -t gh_content_debug) || die "Can't create temp file."
-store_gh_search_debug=$(mktemp -t gh_search_debug) || die "Can't create temp file."
-store_grep_extended_debug=$(mktemp -t grep_extended_debug) || die "Can't create temp file."
-store_input_list=$(mktemp -t input_list) || die "Can't create temp file."
-store_tee_append=$(mktemp -t tee_append) || die "Can't create temp file."
-declare -a temp_files=(
-	"$store_bat_debug"
-	"$store_file_contents"
-	"$store_fzf_port"
-	"$store_gh_content_debug"
-	"$store_gh_search_debug"
-	"$store_grep_extended_debug"
-	"$store_input_list"
-	"$store_tee_append"
-)
 
-cleanup() {
-	# TODO: find a better solution; the while loop requires some time to terminate and
-	# might leave some files behind if the 'cleanup' function is run immediately upon exit
-	sleep 2 &
-	wait
-	$debug_mode && printf "%bDebug mode was ON, the following files weren't deleted.%b\n" "$YELLOW_NORMAL" "$COLOR_RESET"
-	for file in "${temp_files[@]}"; do
-		# Use the 'find' command with a wildcard to retrieve all matching files.
-		find "${file}"* 2>/dev/null | while read -r matching_file; do
-			# These files are not really useful for debugging and can always be deleted.
-			if [[ $matching_file == ${store_file_contents}* ]]; then
-				rm -f "$matching_file"
-			elif ! $debug_mode || [[ ! -s $matching_file ]]; then
-				rm -f "$matching_file"
-			else
-				printf "\t%s\n" "$matching_file"
-			fi
-		done
-	done
-}
+date_prefix=$(date -u +%Y-%m-%dT%H-%M-%S)
+# Default directory for trivial files
+scratch_directory=$(mktemp -dt "$date_prefix.gh_find_code") || die "Can't create directory."
+store_input_list="${scratch_directory}/input_list"
+store_tee_append="${scratch_directory}/tee_append"
+store_fzf_port="${scratch_directory}/fzf_port"
+store_file_contents="${scratch_directory}/file_content"
+
+# Debug directory
+debug_directory=$(mktemp -dt "$date_prefix.gh_find_code.debug") || die "Can't create debug directory."
+store_bat_debug="${debug_directory}/bat_debug"
+store_grep_extended_debug="${debug_directory}/grep_extended_debug"
+store_gh_search_debug="${debug_directory}/gh_search_debug"
+store_gh_content_debug="${debug_directory}/gh_content_debug"
 
 # This function validates the version of a tool.
 check_version() {
@@ -135,7 +127,6 @@ ${WHITE_BOLD}Flags${COLOR_RESET}
 
 ${WHITE_BOLD}Hotkeys${COLOR_RESET}
   ${GREEN_NORMAL}?     ${COLOR_RESET}  help
-  ${GREEN_NORMAL};     ${COLOR_RESET}  quick jump
   ${GREEN_NORMAL}ctrl-b${COLOR_RESET}  open the file in the browser
   ${GREEN_NORMAL}ctrl-e${COLOR_RESET}  open the file content in the '\$EDITOR'
   ${GREEN_NORMAL}ctrl-o${COLOR_RESET}  open the search query in the browser
@@ -273,6 +264,10 @@ gh_query() {
 
 			# listed items
 			while IFS=$'\t' read -r index owner_repo_name file_name file_path patterns; do
+				# https://github.com/junegunn/fzf/issues/398
+				# TODO: Improve the solution for terminating this while loop, when the script is exited.
+				# Tested with 'sudo opensnoop -n bash', without a break check it
+				# keeps going through the data list.
 				# Check if the parent process is still running or kill the loop
 				! kill -0 "$PPID" 2>/dev/null && break
 
@@ -516,16 +511,15 @@ view_contents() {
 : | fzf \
 	--ansi \
 	--bind $'start:execute-silent(echo $FZF_PORT > $store_fzf_port)+reload:gh_query {q}' \
-	--bind "change:first+reload:sleep 0.75; gh_query {q}" \
+	--bind "change:first+reload:sleep 0.65; gh_query {q} || true" \
 	--bind 'ctrl-b:execute-silent:gh browse --repo {4} {5}:{1}' \
 	--bind 'ctrl-e:execute:[[ -n {q} && -n {} ]] && open_in_editor=true view_contents {}' \
 	--bind 'ctrl-o:execute-silent:open_query_in_browser {q}' \
-	--bind 'ctrl-r:reload:gh_query {q}' \
+	--bind 'ctrl-r:reload:gh_query {q} || true' \
 	--bind 'ctrl-u:clear-query' \
 	--bind 'enter:execute:[[ -n {q} && -n {} ]] && open_in_pager=true view_contents {}' \
 	--bind "esc:become:" \
 	--bind '?:toggle-preview+change-preview(print_help_text)+change-preview-window:~0:+1' \
-	--bind ';:jump' \
 	--bind 'load:change-preview([[ -n {q} && -n {} ]] && view_contents {})+change-preview-window:+{1}+3/3' \
 	--bind 'tab:toggle-preview+change-preview-window(hidden|nohidden:+{1}+3/3)+change-preview:[[ -n {q} && -n {} ]] && view_contents {}' \
 	--border block \
@@ -540,7 +534,6 @@ view_contents() {
 	--height=100% \
 	--header-lines 0 \
 	--info hidden \
-	--jump-labels 'abcdefghijklmnopqrstuvwxyz' \
 	--layout reverse \
 	--listen \
 	--no-multi \
